# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('ran_ready_function', models.DateTimeField(null=True)),
                ('current_quest_num', otree.db.models.IntegerField(null=True)),
                ('s1_answered', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('s2_answered', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('s3_answered', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('s4_answered', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('s5_answered', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('group_ff_points', otree.db.models.IntegerField(default=0, null=True)),
                ('question_sequence', otree.db.models.StringField(default='', max_length=10000, null=True)),
                ('all_play', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('total_cont', otree.db.models.CurrencyField(null=True)),
                ('indiv_share', otree.db.models.CurrencyField(null=True)),
                ('excluded_player', otree.db.models.StringField(max_length=10000, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_vote_famfeud_group', to='otree.Session')),
            ],
            options={
                'db_table': 'pg_vote_famfeud_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('playerlabel', otree.db.models.StringField(choices=[('Player A', 'Player A'), ('Player B', 'Player B'), ('Player C', 'Player C'), ('Player D', 'Player D'), ('Player E', 'Player E')], max_length=10000, null=True)),
                ('treatment', otree.db.models.StringField(choices=[('voting', 'voting'), ('novoting', 'novoting')], max_length=10000, null=True)),
                ('city', otree.db.models.StringField(choices=[('münchen', 'münchen'), ('heidelberg', 'heidelberg')], max_length=10000, null=True)),
                ('contribution', otree.db.models.CurrencyField(null=True, verbose_name='What do you want to contribute to the project?')),
                ('myvotes', otree.db.models.IntegerField(null=True)),
                ('plays', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True)),
                ('vote_A', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Player A')),
                ('vote_B', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Player B')),
                ('vote_C', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Player C')),
                ('vote_D', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Player D')),
                ('vote_E', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Player E')),
                ('guess_sequence', otree.db.models.StringField(default='', max_length=10000, null=True)),
                ('ff_points', otree.db.models.IntegerField(default=0, null=True)),
                ('num_guesses', otree.db.models.IntegerField(default=0, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pg_vote_famfeud.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_vote_famfeud_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_vote_famfeud_player', to='otree.Session')),
            ],
            options={
                'db_table': 'pg_vote_famfeud_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_vote_famfeud_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'pg_vote_famfeud_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_vote_famfeud.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_vote_famfeud.Subsession'),
        ),
    ]
