# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_vote_famfeud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='silo_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='exclude_none',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name="I don't want to vote for any player."),
        ),
        migrations.AddField(
            model_name='player',
            name='ivoted',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
