# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-19 07:48
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_vote_famfeud', '0002_auto_20180920_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='control1',
            field=otree.db.models.IntegerField(null=True, verbose_name='Wie viele Taler haben Sie auf Ihrem privaten Konto, wenn Sie 3 Taler auf das Gruppenkonto einzahlen?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control2',
            field=otree.db.models.IntegerField(null=True, verbose_name='20 Taler wurden insgesamt in das Gruppenkonto eingezahlt. Wie viele Taler erhalten Sie am Ende aus dem Gruppenkonto?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control3a',
            field=otree.db.models.StringField(choices=[('wahr', 'wahr'), ('falsch', 'falsch')], max_length=10000, null=True, verbose_name='Es kann sein, dass verschiedene Gruppenmitglieder unterschiedlich viele Taler aus dem Gruppenkonto erhalten.'),
        ),
        migrations.AddField(
            model_name='player',
            name='control3b',
            field=otree.db.models.StringField(choices=[('wahr', 'wahr'), ('falsch', 'falsch')], max_length=10000, null=True, verbose_name='Am Ende der ersten Stufe einer jeweiligen Runde wissen Sie, wie viel jedes Gruppenmitglied ins Gruppenkonto eingezahlt hat.'),
        ),
        migrations.AddField(
            model_name='player',
            name='control3c',
            field=otree.db.models.StringField(choices=[('wahr', 'wahr'), ('falsch', 'falsch')], max_length=10000, null=True, verbose_name='Sie spielen in jeder Runde in einer neuen Gruppe mit anderen Personen'),
        ),
        migrations.AddField(
            model_name='player',
            name='control3d',
            field=otree.db.models.StringField(choices=[('wahr', 'wahr'), ('falsch', 'falsch')], max_length=10000, null=True, verbose_name='Sollten Sie in einer Runde vom Gruppenspiel ausgeschlossen werden, so können Sie in der nächsten Runde nicht an der Aufteilungsentscheidung teilnehmen.'),
        ),
        migrations.AddField(
            model_name='player',
            name='control4',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Für den Ausschluss von wie vielen Gruppenmitgliedern können Sie maximal stimmen?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control5',
            field=otree.db.models.IntegerField(null=True, verbose_name='Wie viele Taler kostet es Sie, wenn Sie ein Gruppenmitglied ausschließen?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control6',
            field=otree.db.models.StringField(choices=[('ja', 'ja'), ('nein', 'nein')], max_length=10000, null=True, verbose_name='Sie erhalten zwei Stimmen. Dürfen Sie an dem Gruppenspiel teilnehmen?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control7control',
            field=otree.db.models.StringField(choices=[('Alleine', 'Alleine'), ('Mit 4 Teilnehmern, die in Stufe 1 dieser Runde nicht in meiner Gruppe waren', 'Mit 4 Teilnehmern, die in Stufe 1 dieser Runde nicht in meiner Gruppe waren'), ('Mit den 4 Teilnehmern, die in Stufe 1 dieser Runde in meiner Gruppe waren', 'Mit den 4 Teilnehmern, die in Stufe 1 dieser Runde in meiner Gruppe waren')], max_length=10000, null=True, verbose_name='Mit wem spielen Sie das Gruppenspiel?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control7exclude',
            field=otree.db.models.StringField(choices=[('Alleine', 'Alleine'), ('Mit 4 Teilnehmern, die in Stufe 1 dieser Runde nicht in meiner Gruppe waren', 'Mit 4 Teilnehmern, die in Stufe 1 dieser Runde nicht in meiner Gruppe waren'), ('Mit den Teilnehmern meiner Gruppe, die nicht ausgeschlossen wurden', 'Mit den Teilnehmern meiner Gruppe, die nicht ausgeschlossen wurden'), ('Mit den ausgeschlossenen Gruppenmitgliedern aus dieser Runde', 'Mit den ausgeschlossenen Gruppenmitgliedern aus dieser Runde')], max_length=10000, null=True, verbose_name='Mit wem spielen Sie das Gruppenspiel?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control8',
            field=otree.db.models.StringField(choices=[('Nichts', 'Nichts'), ('Er wird allen Gruppenmitgliedern gezeigt und ich verdiene einen Taler', 'Er wird allen Gruppenmitgliedern gezeigt und ich verdiene einen Taler'), ('Er wird allen Gruppenmitgliedern gezeigt und die Gruppe bekommt einen Spielpunkt', 'Er wird allen Gruppenmitgliedern gezeigt und die Gruppe bekommt einen Spielpunkt')], max_length=10000, null=True, verbose_name='Was passiert, wenn Sie einen richtigen Begriff im Gruppenspiel eingeben?'),
        ),
        migrations.AddField(
            model_name='player',
            name='control_tries',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ff_experience',
            field=otree.db.models.IntegerField(null=True, verbose_name='Bitte klicken Sie auf die Skala, um Ihre Erfahrung während des letzten Gruppenspiels zu bewerten. 1 bedeutet schlecht und 5 gut.'),
        ),
        migrations.AddField(
            model_name='player',
            name='ff_valuation',
            field=otree.db.models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Bitte klicken Sie auf die Skala, um ihre Zahlungsbereitschaft auszuwählen.'),
        ),
        migrations.AddField(
            model_name='player',
            name='germanplayerlabel',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='payround',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='plays_bonusFF',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q1',
            field=otree.db.models.IntegerField(null=True, verbose_name='Was denken Sie, wie viele Taler sollte man zum Gruppenkonto beitragen?'),
        ),
        migrations.AddField(
            model_name='player',
            name='q10',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Möchten Sie uns noch etwas mitteilen? Hier ist die Gelegenheit dazu!'),
        ),
        migrations.AddField(
            model_name='player',
            name='q2',
            field=otree.db.models.StringField(choices=[('Ja', 'Ja'), ('Ich bin mir unsicher', 'Ich bin mir unsicher'), ('Nein, die meisten anderen denken man sollte mehr beitragen', 'Nein, die meisten anderen denken man sollte mehr beitragen'), ('Nein, die meisten anderen denken man sollte weniger beitragen', 'Nein, die meisten anderen denken man sollte weniger beitragen')], max_length=10000, null=True, verbose_name='Denken Sie, die meisten anderen sehen das auch wie Sie?'),
        ),
        migrations.AddField(
            model_name='player',
            name='q3',
            field=otree.db.models.StringField(choices=[('Ich habe rein zufällig meine Stimme vergeben', 'Ich habe rein zufällig meine Stimme vergeben'), ('Ich wollte Gruppenmitglieder für Ihr Verhalten in der vorherigen Stufe bestrafen', 'Ich wollte Gruppenmitglieder für Ihr Verhalten in der vorherigen Stufe bestrafen'), ('Ich wollte andere von der Last des Gruppenspiels befreien', 'Ich wollte andere von der Last des Gruppenspiels befreien'), ('Ich wollte ausprobieren was passiert', 'Ich wollte ausprobieren was passiert'), ('Ich habe in keiner Runde eine Stimme abgegeben', 'Ich habe in keiner Runde eine Stimme abgegeben')], max_length=10000, null=True, verbose_name='In jeder Runde hatten Sie die Möglichkeit, Gruppenmitglieder vom Gruppenspiel auszuschließen. Welche Überlegungen haben Sie dabei angestellt? (Bitte wählen Sie die Option, die am besten passt.)'),
        ),
        migrations.AddField(
            model_name='player',
            name='q4',
            field=otree.db.models.StringField(choices=[('Rein zufällig', 'Rein zufällig'), ('Sie wollten Gruppenmitglieder für Ihr Verhalten in der vorherigen Stufe bestrafen', 'Sie wollten Gruppenmitglieder für Ihr Verhalten in der vorherigen Stufe bestrafen'), ('Sie wollten andere von der Last des Gruppenspiels befreien', 'Sie wollten andere von der Last des Gruppenspiels befreien'), ('Sie wollten andere von der Last des Gruppenspiels befreien', 'Sie wollten andere von der Last des Gruppenspiels befreien'), ('Sie wollten ausprobieren was passiert', 'Sie wollten ausprobieren was passiert')], max_length=10000, null=True, verbose_name='Was denken Sie, warum haben andere Teilnehmer dafür gestimmt, Gruppenmitglieder auszuschließen?'),
        ),
        migrations.AddField(
            model_name='player',
            name='q5',
            field=otree.db.models.IntegerField(null=True, verbose_name='Bitte geben Sie ihr Alter an'),
        ),
        migrations.AddField(
            model_name='player',
            name='q6',
            field=otree.db.models.StringField(choices=[('männlich', 'männlich'), ('weiblich', 'weiblich'), ('keine Angabe', 'keine Angabe')], max_length=10000, null=True, verbose_name='Bitte geben Sie ihr Geschlecht an'),
        ),
        migrations.AddField(
            model_name='player',
            name='q7',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Bitte geben Sie ihr Studienfach an'),
        ),
        migrations.AddField(
            model_name='player',
            name='q8',
            field=otree.db.models.IntegerField(null=True, verbose_name='Wie oft haben Sie bereits an einer ökonomischen Laborstudie teilgenommen (auch außerhalb dieses Labors)?'),
        ),
        migrations.AddField(
            model_name='player',
            name='q9',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Wie viele Teilnehmerinnen oder Teilnehmer in diesem Raum haben Sie schon vor dem Experiment gekannt?'),
        ),
        migrations.AddField(
            model_name='player',
            name='random_ff_valuation',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='round_payoff',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='indiv_share',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_cont',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='contribution',
            field=otree.db.models.IntegerField(null=True, verbose_name='Ihr Betrag'),
        ),
        migrations.AlterField(
            model_name='player',
            name='exclude_none',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Ich möchte kein Gruppenmitglied ausschließen.'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote_A',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Teilnehmer A'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote_B',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Teilnehmer B'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote_C',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Teilnehmer C'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote_D',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Teilnehmer D'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote_E',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], verbose_name='Teilnehmer E'),
        ),
    ]
