# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-30 13:47
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_vote_famfeud', '0003_auto_20181119_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='control4m',
            field=otree.db.models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Für den Ausschluss von wie vielen Gruppenmitgliedern können Sie maximal stimmen?'),
        ),
    ]
