# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 11:48
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_vote_famfeud', '0004_player_control4m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='control5',
            field=otree.db.models.IntegerField(choices=[(0, 0), (0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2)], null=True, verbose_name='Wie viele Taler kostet es Sie, wenn Sie ein Gruppenmitglied ausschließen?'),
        ),
    ]
