# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 16:34
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_vote_famfeud', '0006_auto_20181203_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='control5',
            field=otree.db.models.StringField(choices=[('0 Taler  ', '0 Taler  '), ('0,5 Taler  ', '0,5 Taler  '), ('1 Taler  ', '1 Taler  '), ('1,5 Taler  ', '1,5 Taler  '), ('2 Taler  ', '2 Taler  ')], max_length=10000, null=True, verbose_name='Wie viele Taler kostet es Sie, wenn Sie ein Gruppenmitglied ausschließen?'),
        ),
    ]
